version: '3.8'

networks:
  rotten_net:
    driver: bridge

services:
  rabbitmq:
    image: rabbitmq:3.11.24-management
    networks: 
    - rotten_net
    environment:
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 5672:5672
      - 15672:15672

  db:
    image: postgres
    networks: 
      - rotten_net
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234

  db-receiver:
    build: 
      context: ./db-receiver
      dockerfile: Dockerfile-db
    image: db-receiver
    networks: 
    - rotten_net
    ports:
      - 5000:5000
    depends_on:
      - db
      - rabbitmq

  api-publisher:
    build: 
      context: ./api-publisher
      dockerfile: Dockerfile-api
    image: api-publisher
    networks: 
    - rotten_net
    ports:
      - 8000:8000
    depends_on:
      - rabbitmq
  
  
