apiVersion: apps/v1
kind: Deployment
metadata:
  name: "app-deployment"
  labels:
    app: "app"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "app"
  template:
    metadata:
      labels:
        app: "app"
    spec:
      containers:
        - name: "api-publisher"
          image: nicole/api-publisher
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
            limits:
              memory: 250Mi
---
apiVersion: v1
kind: Service
metadata:
  name: "app-service"
spec:
  selector:
    app: "app"
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  # type: LoadBalancer
# ---
# kind: Service
# apiVersion: v1
# metadata:
#   name: rabbitmq
# spec:
#   type: ExternalName
#   externalName: localhost
   