apiVersion: apps/v1
kind: Deployment
metadata:
  name: "app-deployment"
  labels:
    app: "app"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "app"
  template:
    metadata:
      labels:
        app: "app"
    spec:
      containers:
        - name: "api-publisher"
          image: nicole/api-publisher
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
            limits:
              memory: 250Mi
          livenessProbe:
            httpGet:
                port: 8000
                path: /alive
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: "app-service"
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: "app"
  type: LoadBalancer
---
kind: Service
apiVersion: v1
metadata:
  name: rabbitmq
spec:
  type: ExternalName
  externalName: localhost
   