apiVersion: apps/v1
kind: Deployment
metadata:
  name: "receiver-deployment"
  labels:
    app: "receiver"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "receiver"
  template:
    metadata:
      labels:
        app: "receiver"
    spec:
      containers:
        - name: "db-receiver"
          image: nicole/db-receiver
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          # envFrom:
          #   - configMapRef:
          #       name: postgres-config
          resources:
            limits:
              memory: 250Mi
            requests:
              cpu: 200m
              memory: 200Mi
---
apiVersion: v1
kind: Service
metadata:
  name: "receiver"
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: "receiver"
  type: LoadBalancer
---
kind: Service
apiVersion: v1
metadata:
  name: postgres
spec:
  type: ExternalName
  externalName: localhost
   