apiVersion: apps/v1
kind: Deployment
metadata:
  name: "receiver-deployment"
  labels:
    app: "receiver"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "receiver"
  template:
    metadata:
      labels:
        app: "receiver"
    spec:
      containers:
        - name: "db-receiver"
          image: nicole/db-receiver
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: postgres-config
          resources:
            limits:
              memory: 250Mi
            requests:
              cpu: 200m
              memory: 200Mi
---
apiVersion: v1
kind: Service
metadata:
  name: "receiver"
spec:
  selector:
    app: "app"
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  # type: LoadBalancer
# ---
# kind: Service
# apiVersion: v1
# metadata:
#   name: postgres
# spec:
#   type: ExternalName
#   externalName: localhost
   
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: ExternalName
  externalName: localhost
  ports:
    - port: 5432
      targetPort: 5432
